version: "3.9"

services:
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sl_postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: space_launcher
